language: go

services:
  - docker

sudo: required

go:
  - 1.8

before_install:
  - sudo sh -c 'echo "deb https://apt.dockerproject.org/repo ubuntu-precise main" > /etc/apt/sources.list.d/docker.list'
  - sudo apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
  - sudo apt-get update
  - sudo apt-key update
  - sudo apt-get install docker-engine
  - curl -L https://github.com/docker/compose/releases/download/1.13.0/docker-compose-`uname -s`-`uname -m` | sudo tee /usr/local/bin/docker-compose > /dev/null
  - sudo chmod +x /usr/local/bin/docker-compose
  - docker-compose -v
  - docker -v

install:
  - make

before_script:
  - docker-compose up --build -d
  - sleep 2

script:
  - make integration-tests
