version: '2'

services:
  store:
    image: postgres:9.4
    ports:
      - 54321:54321
    volumes:
      - ./db/postgres/:/docker-entrypoint-initdb.d/
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

  documents:
    image: golang:1.8-alpine
    volumes:
      - ./:/go/src/github.com/trussle/snowy
    working_dir: /go/src/github.com/trussle/snowy
    depends_on:
      - store
    environment:
      AWS_ID: "${AWS_ID}"
      AWS_SECRET: "${AWS_SECRET}"
      AWS_REGION: "${AWS_REGION}"
      AWS_TOKEN: "${AWS_TOKEN}"
      AWS_BUCKET: "${AWS_BUCKET}"
